
Object.defineProperties Function::,
    apply2 : value : Function::apply.bind Function::
    call2 : value : Function::call.bind Function::

Object.defineProperties Function::,

    apply : value : ->
        console.debug { arguments }
        @apply2 arguments...

    call : value : ->
        console.debug { arguments }
        @call2 arguments...


max = 0
logg = console.debug
log = ->
    throw max if max++ > 10
    logg arguments...

reflect = Reflect

proxyHandlers = ->
    apply                       : -> log("app2ly:", ...arguments); reflect.apply arguments...
    construct                   : -> log("construct:", ...arguments); reflect.construct arguments...
    defineProperty              : -> log("defineProperty:", ...arguments); reflect.defineProperty arguments...
    deleteProperty              : -> log("deleteProperty:", ...arguments); reflect.deleteProperty arguments...
    get                         : -> log("get:", ...arguments); reflect.get arguments...
    getOwnPropertyDescriptor    : -> log("getOwnPropertyDescriptor:", ...arguments); reflect.getOwnPropertyDescriptor arguments...
    getPrototypeOf              : -> log("getPrototypeOf:", ...arguments); reflect.getPrototypeOf arguments...
    has                         : -> log("has:", ...arguments); reflect.has arguments...
    isExtensible                : -> log("isExtensible:", ...arguments); reflect.isExtensible arguments...
    ownKeys                     : -> log("ownKeys:", ...arguments); reflect.ownKeys arguments...
    preventExtensions           : -> log("preventExtensions:", ...arguments); reflect.preventExtensions arguments...
    set                         : -> log("set:", ...arguments); reflect.set arguments...
    setPrototypeOf              : -> log("setPrototypeOf:", ...arguments); reflect.setPrototypeOf arguments...


console.log window.Array

window.Function.constructor = new Proxy( Function.constructor, proxyHandlers() )
window.Function.__proto__ = new Proxy( Function.__proto__, proxyHandlers() )
window.Function = new Proxy( Function, proxyHandlers() )
window.Object = new Proxy( Object, proxyHandlers() )
window.Array = new Proxy( Array, proxyHandlers() )
window.Array.__proto__ = new Proxy( Array, proxyHandlers() )
window.String = new Proxy( String, proxyHandlers() )
window.Number = new Proxy( Number, proxyHandlers() )
window.Boolean = new Proxy( Boolean, proxyHandlers() )
